### ISSUE TITLE
Add backend to this app

### ISSUE THREAD

**Issue by deepakgohil009** [vijayyprajapati/Share-Your-Bookmarks#136]
It would be great if we add backend to this app coz data.json file is not scalable option.

@vijayyprajapati add hacktober label to this issue coz this issue seems relevant for hacktober.

**Comment by deepakgohil009** [comment]
I would like to work on this issue. Assign it to me.

**Comment by vijayyprajapati** [comment]
Go ahead @deepakgohil009

**Comment by deepakgohil009** [comment]
Thanks @vijayyprajapati for assigning me during development of backend I may require to create couple of issues. So I hope you approve that as well.
