### ISSUE TITLE
Integrate frontend with backend

### ISSUE THREAD

**Issue by deepakgohil009** [vijayyprajapati/Share-Your-Bookmarks#141]
New Backend is being made in Node, Express and MongoDB. So we have to integrate frontend such that data comes from backend instead of data.json

**Comment by deepakgohil009** [comment]
@vijayyprajapati This is the trailing issue for making backend and then integrating it.
So do assign it to me.

**Comment by vijayyprajapati** [comment]
Sure @deepakgohil009

**Comment by deepakgohil009** [comment]
@vijayyprajapati Thanks for assigning me this issue please have a look on deploy issue as well. I will complete both the deployment and integration by tomorrow.
