### ISSUE TITLE
Add "Steps to contribute" in the readme file.

### ISSUE THREAD

**Issue by vijayyprajapati** [vijayyprajapati/Share-Your-Bookmarks#17]

**Comment by SiddhiKhade** [comment]
Hi, i would really appreciate it if you assigned this issue to me, thanks!

**Comment by vijayyprajapati** [comment]
Go ahead @SiddhiKhade

**Comment by vijayyprajapati** [comment]
You can make two PRs.
The first one is by updating the readme and the second one is by adding your profile.

**Comment by vijayyprajapati** [comment]
Anyone else wanna work on this issue.

**Comment by sayan3270** [comment]
i want to wor on this issue

**Comment by vijayyprajapati** [comment]
Go ahead @sayan3270

**Comment by dubeyanant** [comment]
Can I work on this issue?
---
- I will add step by step guide on how to fork, clone, edit and make a pull request.
- I will add what should be edited in `data.json`.
---
If this is good enough please assign this to me.

**Comment by vijayyprajapati** [comment]
Hey @dubeyanant 
This issue has already been assigned to @sayan3270
If @sayan3270 does not raise a pull request by the end of today then I will assign it to you.
