### ISSUE TITLE
Improve user details page.

### ISSUE THREAD

**Issue by vijayyprajapati** [vijayyprajapati/Share-Your-Bookmarks#18]

**Comment by syprogrammer** [comment]
hello can you assign me

**Comment by vijayyprajapati** [comment]
Sure @syprogrammer

**Comment by vijayyprajapati** [comment]
You can make two PRs.
The first is by improving the user's detail page and the second is by adding your profile.

**Comment by syprogrammer** [comment]
check the design if it is ok : https://bit.ly/3el55mT

**Comment by syprogrammer** [comment]
book img at top of name or at top "share your bookmark logo"

**Comment by vijayyprajapati** [comment]
Remove both of them.

**Comment by syprogrammer** [comment]
@vijayyprajapati check if it is ok : https://bit.ly/3RZLI09

**Comment by vijayyprajapati** [comment]
Hey @syprogrammer 
it really looks nice to me. You have done a great job. 
You can raise a PR to add your design to the repository or you can do these changes on your own and raise a PR about the changes.
