### ISSUE TITLE
[FEATURE] Add scroll to top button for better user experience

### ISSUE THREAD

**Issue by heyaadarsh** [vijayyprajapati/Share-Your-Bookmarks#203]
Hi @vijayyprajapati,
I visited the website, and the geeky UI is really really impressive, but I saw that a "scroll to top button" is missing here. I think if we add a scroll to top button it will enhance the user experience. I can add a sticky scroll to top button, matching to the current design. I am very curious to do that!
May you please assign it to me?

**Comment by vijayyprajapati** [comment]
Go ahead @heyaadarsh

**Comment by heyaadarsh** [comment]
> Go ahead @heyaadarsh

Thanks for assigning me @vijayyprajapati! I will create a PR by today itself.

**Comment by Ishikasaraf20** [comment]
hey @vijayyprajapati can you assign this issue to me i can work on it

**Comment by vijayyprajapati** [comment]
Hey @Ishikasaraf20  this issue already has been assigned
You can add your profile and bookmark links and raise a PR.

**Comment by heyaadarsh** [comment]
> hey @vijayyprajapati can you assign this issue to me i can work on it

@Ishikasaraf20 This issue was generated by me and also assigned to me. I have started working on it and will create a PR very soon. I think you are new to open source, analyze the project carefully, create relevant issues by yourself and work on that. I hope you understand.

**Comment by heyaadarsh** [comment]
> Go ahead @heyaadarsh

Hi @vijayyprajapati 
I have added "Scroll to Top Button" and created a PR #214, please check it out and merge it into this wonderful repo and if you have any suggestions then I'm ready to work on that.
Thank You!
