### ISSUE TITLE
Improve the mobile responsiveness of the website.

### ISSUE THREAD

**Issue by vijayyprajapati** [vijayyprajapati/Share-Your-Bookmarks#31]

**Comment by vijayyprajapati** [comment]
Go ahead @abitsalihu

**Comment by abitsalihu** [comment]
Hey @vijayyprajapati, I noticed that the website is actually pretty responsive, is there any part in particular that isn't that I can work on? The only non responsive part I could find was the text `Click here to see  Contribution Guidelines`.

**Comment by vijayyprajapati** [comment]
You need to fix that only.
