### ISSUE TITLE
Design a favicon for the website.

### ISSUE THREAD

**Issue by vijayyprajapati** [vijayyprajapati/Share-Your-Bookmarks#32]

**Comment by DarkSoul26** [comment]
@vijayyprajapati I'm experienced in this domain, so I would like to contribute to it.

**Comment by vijayyprajapati** [comment]
Do ahead @DarkSoul26

**Comment by DarkSoul26** [comment]
#35 can you please take a look into this pull request?

**Comment by DarkSoul26** [comment]
Hi @vijayyprajapati can you take a look into #35 ?

**Comment by vijayyprajapati** [comment]
Sure @dubeyanant
