### ISSUE TITLE
Add "Table of Content" in the README.md file

### ISSUE THREAD

**Issue by dubeyanant** [vijayyprajapati/Share-Your-Bookmarks#69]
Add a Table of Content so that viewer can directly go to a particular section of the readme file.

**Comment by sandilya27** [comment]
please assign it to me

**Comment by vijayyprajapati** [comment]
Hey @dubeyanant 
Do you want to work on this issue?

**Comment by dubeyanant** [comment]
> Hey @dubeyanant Do you want to work on this issue?

yes

**Comment by vijayyprajapati** [comment]
Okay then do it.
