### ISSUE TITLE
Improve the hover effect on bookmark links in details page.

### ISSUE THREAD

**Issue by vijayyprajapati** [vijayyprajapati/Share-Your-Bookmarks#75]

**Comment by vijayyprajapati** [comment]
You just need to remove the vibration when we hover from one link to another.

**Comment by vikash485** [comment]
Hey @vijayyprajapati, can I try this issue?

**Comment by vijayyprajapati** [comment]
Sure @vikash485

**Comment by vikash485** [comment]
I have made a pr, please check and verify @vijayyprajapati
