### ISSUE TITLE
Change the home link  to slide back to previous page

### ISSUE THREAD

**Issue by Snehil0603** [vijayyprajapati/Share-Your-Bookmarks#80]
Currently to go from user detail page to home page we have to click on home . How about adding an arrow like the one shown below.
<img src="https://user-images.githubusercontent.com/96441611/196192422-7c4ab670-859c-4251-a49f-de790d2bb9ab.png" width="400">
<img src="https://user-images.githubusercontent.com/96441611/196193659-e3b42eed-7082-4b35-850d-2c8558bbe8bf.png" width="250" >

**Comment by Kabiirk** [comment]
Hi, please assign this issue to me ,thanks.

**Comment by vijayyprajapati** [comment]
Great Idea @Snehil0603 
We can use this arrow beside the home button.
Add an arrow in front of the home and make a button that includes both of them.

**Comment by vijayyprajapati** [comment]
Hey @Snehil0603 
Are you interested in fixing this issue?

**Comment by Snehil0603** [comment]
@vijayyprajapati yes I want to do it

**Comment by Snehil0603** [comment]
@vijayyprajapati I am interested in this issue kindly assign me.

**Comment by vijayyprajapati** [comment]
Sure @Snehil0603
