### ISSUE TITLE
[FEATURE] A footer to add link to this Github repo.

### ISSUE THREAD

**Issue by Vedant-Manjrekar** [vijayyprajapati/Share-Your-Bookmarks#97]
A footer to add link to this Github repo, so people can know its open-source and more people can contribute.

@vijayyprajapati please assign this issue to me, I can implement this in no time.

**Comment by vijayyprajapati** [comment]
Hey @Vedant-Manjrekar I liked your Idea of adding GitHub repo link but don't add it in the footer instead add it in the upper right corner.

**Comment by vijayyprajapati** [comment]
> Hey @Vedant-Manjrekar I liked your Idea of adding GitHub repo link but don't add it in the footer instead add it in the upper right corner.

I am assigning it to you but make sure to do it as I  said.

**Comment by Vedant-Manjrekar** [comment]
@vijayyprajapati How's this: 
<img width="1439" alt="Screenshot 2022-10-18 at 1 28 02 PM" src="https://user-images.githubusercontent.com/93585735/196372667-a7069439-1004-4652-a712-73a79ded0dd4.png">

**Comment by Vedant-Manjrekar** [comment]
@vijayyprajapati How's this:

I implemented both the concepts, the one you asked and one i suggested. Check it out and let me know which one to final.

1. (Top right)
<img width="1438" alt="Screenshot 2022-10-18 at 7 57 37 PM" src="https://user-images.githubusercontent.com/93585735/196459380-e2b50198-dca4-4692-9846-46791ffcab40.png">

2. (Footer)
<img width="1439" alt="Screenshot 2022-10-18 at 1 28 02 PM" src="https://user-images.githubusercontent.com/93585735/196459407-4d236d3b-01f7-4f6f-b7c2-9a9c7da36442.png">

**Comment by vijayyprajapati** [comment]
First one looks nice but the padding top on the header increased try to fix that.
We can not add the GitHub link in the footer because the number of people supposes to increase to 1000 than to get the link to the GitHub repo users need to scroll so much all the time.

**Comment by Vedant-Manjrekar** [comment]
> First one looks nice but the padding top on the header increased try to fix that. We can not add the GitHub link in the footer because the number of people supposes to increase to 1000 than to get the link to the GitHub repo users need to scroll so much all the time.

### @vijayyprajapati Done 👍🏽
Now the padding space is just like before and logo is adjusted in that much space.

Before (How it is right now on the deployed website) :
<img width="816" alt="Screenshot 2022-10-19 at 12 17 49 PM" src="https://user-images.githubusercontent.com/93585735/196617324-d089b45b-3500-43d9-9b5d-c86de62f56b1.png">

After: 
<img width="815" alt="Screenshot 2022-10-19 at 12 17 35 PM" src="https://user-images.githubusercontent.com/93585735/196617434-4e9e8127-82e0-4bfc-bec9-ba7b4425f68d.png">

**Comment by vijayyprajapati** [comment]
Good job @Vedant-Manjrekar 
It looks nice to me.
Raise a PR.

**Comment by Vedant-Manjrekar** [comment]
@vijayyprajapati Thanks man for the merge, it was great working with you.
